"""
cities.py

Единственный источник правды для словаря CITIES — используется во всех модулях
проекта: weather_miner.py, actuals_miner.py, accuracy_report.py, criteria.py.
Правь только здесь, не копируй словарь по файлам.
"""

CITIES = {
    # --- NORTH AMERICA ---
    "KLGA": {"name": "NYC", "slug": "nyc", "tz": "America/New_York",
             "weather_url": "https://www.wunderground.com/hourly/us/ny/new-york-city/KLGA",
             "windy_url": "https://www.windy.com/40.777/-73.880?radar,40.766,-73.857,12,p:cities"},
    "KLAX": {"name": "Los Angeles", "slug": "los-angeles", "tz": "America/Los_Angeles",
             "weather_url": "https://www.wunderground.com/hourly/us/ca/los-angeles/KLAX",
             "windy_url": "https://www.windy.com/33.938/-118.387?radar,33.930,-118.387,15,p:cities"},
    "KORD": {"name": "Chicago", "slug": "chicago", "tz": "America/Chicago",
             "weather_url": "https://www.wunderground.com/hourly/us/il/chicago/KORD",
             "windy_url": "https://www.windy.com/41.960/-87.932?radar,41.962,-87.929,15,p:cities"},
    "KDAL": {"name": "Dallas", "slug": "dallas", "tz": "America/Chicago",
             "weather_url": "https://www.wunderground.com/hourly/us/tx/dallas/KDAL",
             "windy_url": "https://www.windy.com/32.838/-96.836?radar,32.841,-96.840,15,p:cities"},
    "KMIA": {"name": "Miami", "slug": "miami", "tz": "America/New_York",
             "weather_url": "https://www.wunderground.com/hourly/us/fl/miami/KMIA",
             "windy_url": "https://www.windy.com/25.788/-80.317?radar,25.785,-80.310,15,p:cities"},
    "KHOU": {"name": "Houston", "slug": "houston", "tz": "America/Chicago",
             "weather_url": "https://www.wunderground.com/hourly/us/tx/houston/KHOU",
             "windy_url": "https://www.windy.com/29.646/-95.282?radar,29.643,-95.282,15,p:cities"},
    "KSFO": {"name": "San Francisco", "slug": "san-francisco", "tz": "America/Los_Angeles",
             "weather_url": "https://www.wunderground.com/hourly/us/ca/san-francisco/KSFO",
             "windy_url": "https://www.windy.com/37.620/-122.366?radar,37.617,-122.374,15,p:cities"},
    "KSEA": {"name": "Seattle", "slug": "seattle", "tz": "America/Los_Angeles",
             "weather_url": "https://www.wunderground.com/hourly/us/wa/seatac/KSEA",
             "windy_url": "https://www.windy.com/47.445/-122.313?radar,47.444,-122.310,15,p:cities"},
    "KATL": {"name": "Atlanta", "slug": "atlanta", "tz": "America/New_York",
             "weather_url": "https://www.wunderground.com/hourly/us/ga/atlanta/KATL",
             "windy_url": "https://www.windy.com/33.630/-84.442?radar,33.631,-84.435,15,p:cities"},
    "KBKF": {"name": "Denver", "slug": "denver", "tz": "America/Denver",
             "weather_url": "https://www.wunderground.com/hourly/us/co/aurora/KBKF",
             "windy_url": "https://www.windy.com/39.713/-104.758?radar,39.712,-104.753,15,p:cities"},
    "KAUS": {"name": "Austin", "slug": "austin", "tz": "America/Chicago",
             "weather_url": "https://www.wunderground.com/hourly/us/tx/austin/KAUS",
             "windy_url": "https://www.windy.com/30.183/-97.681?radar,30.185,-97.671,15,p:cities"},
    "CYYZ": {"name": "Toronto", "slug": "toronto", "tz": "America/Toronto",
             "weather_url": "https://www.wunderground.com/hourly/ca/mississauga/CYYZ",
             "windy_url": "https://www.windy.com/43.679/-79.629?radar,43.677,-79.630,15,p:cities"},
    "MMMX": {"name": "Mexico City", "slug": "mexico-city", "tz": "America/Mexico_City",
             "weather_url": "https://www.wunderground.com/hourly/mx/mexico-city/MMMX",
             "windy_url": "https://www.windy.com/19.436/-99.070?radar,19.435,-99.066,15,p:cities"},
    "MPMG": {"name": "Panama City", "slug": "panama-city", "tz": "America/Panama",
             "weather_url": "https://www.wunderground.com/hourly/pa/panama-city/MPMG",
             "windy_url": "https://www.windy.com/8.967/-79.555?radar,8.969,-79.554,15,p:cities"},

    # --- EUROPE ---
    "EGLC": {"name": "London", "slug": "london", "tz": "Europe/London",
             "weather_url": "https://www.wunderground.com/hourly/gb/london/EGLC",
             "windy_url": "https://www.windy.com/51.505/0.055?radar,51.503,0.055,15,p:cities"},
    "LFPG": {"name": "Paris", "slug": "paris", "tz": "Europe/Paris",
             "weather_url": "https://www.wunderground.com/hourly/fr/paris/LFPG",
             "windy_url": "https://www.windy.com/49.015/2.534?radar,49.012,2.535,15,p:cities"},
    "EDDM": {"name": "Munich", "slug": "munich", "tz": "Europe/Berlin",
             "weather_url": "https://www.wunderground.com/hourly/de/munich/EDDM",
             "windy_url": "https://www.windy.com/48.348/11.813?radar,48.345,11.800,15,p:cities"},
    "LIMC": {"name": "Milan", "slug": "milan", "tz": "Europe/Rome",
             "weather_url": "https://www.wunderground.com/hourly/it/milan/LIMC",
             "windy_url": "https://www.windy.com/45.631/8.728?radar,45.624,8.728,15,p:cities"},
    "LEMD": {"name": "Madrid", "slug": "madrid", "tz": "Europe/Madrid",
             "weather_url": "https://www.wunderground.com/hourly/es/madrid/LEMD",
             "windy_url": "https://www.windy.com/40.466/-3.555?radar,40.468,-3.559,14,p:cities"},
    "EHAM": {"name": "Amsterdam", "slug": "amsterdam", "tz": "Europe/Amsterdam",
             "weather_url": "https://www.wunderground.com/hourly/nl/schiphol/EHAM",
             "windy_url": "https://www.windy.com/52.315/4.791?radar,52.311,4.788,14,p:cities"},
    "EPWA": {"name": "Warsaw", "slug": "warsaw", "tz": "Europe/Warsaw",
             "weather_url": "https://www.wunderground.com/hourly/pl/warsaw/EPWA",
             "windy_url": "https://www.windy.com/52.162/20.962?radar,52.164,20.975,14,p:cities"},
    "EFHK": {"name": "Helsinki", "slug": "helsinki", "tz": "Europe/Helsinki",
             "weather_url": "https://www.wunderground.com/hourly/fi/vantaa/EFHK",
             "windy_url": "https://www.windy.com/60.327/24.957?radar,60.319,24.964,14,p:cities"},
    "LTAC": {"name": "Ankara", "slug": "ankara", "tz": "Europe/Istanbul",
             "weather_url": "https://www.wunderground.com/hourly/tr/%C3%A7ubuk/LTAC",
             "windy_url": "https://www.windy.com/40.127/32.996?radar,40.123,33.002,14,p:cities"},

    # --- ASIA ---
    "RKSI": {"name": "Seoul", "slug": "seoul", "tz": "Asia/Seoul",
             "weather_url": "https://www.wunderground.com/hourly/kr/incheon/RKSI",
             "windy_url": "https://www.windy.com/37.468/126.452?radar,37.466,126.448,14,p:cities"},
    "RKPK": {"name": "Busan", "slug": "busan", "tz": "Asia/Seoul",
             "weather_url": "https://www.wunderground.com/hourly/kr/busan/RKPK",
             "windy_url": "https://www.windy.com/35.179/128.938?radar,35.174,128.942,14,p:cities"},
    "RJTT": {"name": "Tokyo", "slug": "tokyo", "tz": "Asia/Tokyo",
             "weather_url": "https://www.wunderground.com/hourly/jp/tokyo/RJTT",
             "windy_url": "https://www.windy.com/35.553/139.781?radar,35.549,139.779,14,p:cities"},
    "ZBAA": {"name": "Beijing", "slug": "beijing", "tz": "Asia/Shanghai",
             "weather_url": "https://www.wunderground.com/hourly/cn/beijing/ZBAA",
             "windy_url": "https://www.windy.com/40.082/116.603?radar,40.081,116.603,14,p:cities"},
    "ZSPD": {"name": "Shanghai", "slug": "shanghai", "tz": "Asia/Shanghai",
             "weather_url": "https://www.wunderground.com/hourly/cn/shanghai/ZSPD",
             "windy_url": "https://www.windy.com/31.146/121.800?radar,31.139,121.804,14,p:cities"},
    "ZGSZ": {"name": "Shenzhen", "slug": "shenzhen", "tz": "Asia/Shanghai",
             "weather_url": "https://www.wunderground.com/hourly/cn/shenzhen/ZGSZ",
             "windy_url": "https://www.windy.com/22.639/113.803?radar,22.642,113.808,14,p:cities"},
    "ZUCK": {"name": "Chongqing", "slug": "chongqing", "tz": "Asia/Shanghai",
             "weather_url": "https://www.wunderground.com/hourly/cn/chongqing/ZUCK",
             "windy_url": "https://www.windy.com/29.717/106.639?radar,29.725,106.660,14,p:cities"},
    "ZUUU": {"name": "Chengdu", "slug": "chengdu", "tz": "Asia/Shanghai",
             "weather_url": "https://www.wunderground.com/hourly/cn/chengdu/ZUUU",
             "windy_url": "https://www.windy.com/30.576/103.951?radar,30.563,103.956,13,p:cities"},
    "WSSS": {"name": "Singapore", "slug": "singapore", "tz": "Asia/Singapore",
             "weather_url": "https://www.wunderground.com/hourly/sg/singapore/WSSS",
             "windy_url": "https://www.windy.com/1.368/103.983?radar,1.347,103.985,13,p:cities"},
    "VILK": {"name": "Lucknow", "slug": "lucknow", "tz": "Asia/Kolkata",
             "weather_url": "https://www.wunderground.com/hourly/in/lucknow/VILK",
             "windy_url": "https://www.windy.com/26.760/80.890?radar,26.757,80.888,13,p:cities"},
    "WMKK": {"name": "Kuala Lumpur", "slug": "kuala-lumpur", "tz": "Asia/Kuala_Lumpur",
             "weather_url": "https://www.wunderground.com/hourly/my/sepang-district/WMKK",
             "windy_url": "https://www.windy.com/2.746/101.714?radar,2.734,101.710,13,p:cities"},
    # "WIHH": {"name": "Jakarta", "slug": "jakarta", "tz": "Asia/Jakarta",
    #          "weather_url": "https://www.wunderground.com/hourly/id/jakarta/WIHH",
    #          "windy_url": "https://www.windy.com/-6.268/106.892?radar,-6.269,106.909,13,p:cities"},
    "ZHHH": {"name": "Wuhan", "slug": "wuhan", "tz": "Asia/Shanghai",
             "weather_url": "https://www.wunderground.com/hourly/cn/wuhan/ZHHH",
             "windy_url": "https://www.windy.com/30.783/114.206?radar,30.770,114.221,13,p:cities"},

    # --- OCEANIA / SOUTH AMERICA ---
    "NZWN": {"name": "Wellington", "slug": "wellington", "tz": "Pacific/Auckland",
             "weather_url": "https://www.wunderground.com/hourly/nz/wellington/NZWN",
             "windy_url": "https://www.windy.com/-41.332/174.807?radar,-41.330,174.815,14,p:cities"},
    "SAEZ": {"name": "Buenos Aires", "slug": "buenos-aires", "tz": "America/Argentina/Buenos_Aires",
             "weather_url": "https://www.wunderground.com/hourly/ar/ezeiza/SAEZ",
             "windy_url": "https://www.windy.com/-34.823/-58.536?radar,-34.822,-58.531,14,p:cities"},
    "SBGR": {"name": "Sao Paulo", "slug": "sao-paulo", "tz": "America/Sao_Paulo",
             "weather_url": "https://www.wunderground.com/hourly/br/guarulhos/SBGR",
             "windy_url": "https://www.windy.com/-23.432/-46.469?radar,-23.433,-46.457,14,p:cities"},

    # --- НОВЫЕ ГОРОДА 29.04.2026 ---
    "OPKC": {"name": "Karachi", "slug": "karachi", "tz": "Asia/Karachi",
             "weather_url": "https://www.wunderground.com/hourly/pk/karachi/OPKC",
             "windy_url": "https://www.windy.com/24.902/67.139?radar,24.901,67.152,15,p:cities"},
    "ZGGG": {"name": "Guangzhou", "slug": "guangzhou", "tz": "Asia/Shanghai",
             "weather_url": "https://www.wunderground.com/hourly/cn/guangzhou/ZGGG",
             "windy_url": "https://www.windy.com/23.392/113.307?radar,23.388,113.307,15,p:cities"},
    "OEJN": {"name": "Jeddah", "slug": "jeddah", "tz": "Asia/Riyadh",
             "weather_url": "https://www.wunderground.com/hourly/sa/jeddah/OEJN",
             "windy_url": "https://www.windy.com/21.685/39.166?radar,21.678,39.166,15,p:cities"},
    # "LTFM": {"name": "Istanbul", "slug": "istanbul", "tz": "Europe/Istanbul",
    #          "weather_url": "https://www.weather.gov/wrh/timeseries?site=LTFM",
    #          "windy_url": "https://www.windy.com/41.262/28.740?radar,41.260,28.739,15,p:cities"},
    # "DNMM": {"name": "Lagos", "slug": "lagos", "tz": "Africa/Lagos",
    #          "weather_url": "https://www.wunderground.com/hourly/ng/lagos/DNMM",
    #          "windy_url": "https://www.windy.com/6.577/3.321?radar,6.578,3.322,15,p:cities"},
    "LLBG": {"name": "Tel Aviv", "slug": "tel-aviv", "tz": "Asia/Jerusalem",
             "weather_url": "https://www.wunderground.com/hourly/il/tel-aviv/LLBG",
             "windy_url": "https://www.windy.com/32.011/34.887?radar,32.009,34.888,15,p:cities"},
    "RPLL": {"name": "Manila", "slug": "manila", "tz": "Asia/Manila",
             "weather_url": "https://www.wunderground.com/hourly/ph/manila/RPLL",
             "windy_url": "https://www.windy.com/14.507/121.004?radar,14.505,121.013,15,p:cities"},
    "ZSQD": {"name": "Qingdao", "slug": "qingdao", "tz": "Asia/Shanghai",
             "weather_url": "https://www.wunderground.com/hourly/cn/qingdao/ZSQD",
             "windy_url": "https://www.windy.com/36.362/120.087?radar,36.359,120.089,15,p:cities"},
    "FACT": {"name": "Cape Town", "slug": "cape-town", "tz": "Africa/Johannesburg",
             "weather_url": "https://www.wunderground.com/hourly/za/matroosfontein/FACT",
             "windy_url": "https://www.windy.com/-33.965/18.602?radar,-33.969,18.604,15,p:cities"},
    "UUWW": {"name": "Moscow", "slug": "moscow", "tz": "Europe/Moscow",
             "weather_url": "https://www.wunderground.com/hourly/ru/moscow/UUWW",
             "windy_url": "https://www.windy.com/55.591/37.261?radar,55.595,37.265,13,p:cities"},
    "RCSS": {"name": "Taipei", "slug": "taipei", "tz": "Asia/Taipei",
             "weather_url": "https://www.wunderground.com/hourly/tw/taipei/RCSS",
             "windy_url": "https://www.windy.com/25.069/121.552?radar,25.065,121.550,13,p:cities"},
    # "VHHH": {"name": "Hong Kong", "slug": "hong-kong", "tz": "Asia/Hong_Kong",
    #          "weather_url": "https://www.weather.gov.hk/en/cis/climat.htm",
    #          "windy_url": "https://www.windy.com/22.302/114.174?radar,22.301,114.174,16,p:cities"},

    # --- НОВЫЕ ГОРОДА 23.08.2026 ---
    "ZSJN": {"name": "Jinan", "slug": "jinan", "tz": "Asia/Shanghai",
             "weather_url": "https://www.wunderground.com/hourly/cn/jinan/ZSJN",
             "windy_url": "https://www.windy.com/36.865/117.203?radar,36.856,117.218,14,p:cities"},
    "ZHCC": {"name": "Zhengzhou", "slug": "zhengzhou", "tz": "Asia/Shanghai",
             "weather_url": "https://www.wunderground.com/hourly/cn/zhengzhou/ZHCC",
             "windy_url": "https://www.windy.com/34.523/113.839?radar,34.516,113.842,14,p:cities"},
}
